---
dependencies:
  requires: requires
  test-requires: test-requires
extra-files:
  - ChangeLog
  - release-notes.md
  -
    share:
      - README.md
  - cpanfile.darkpan
  - cpanm.darkpan
min-perl-version: '5.010'
path:
  exe-files: bin
  pm-module: lib
  tests: t
pm-module: Log::Log4perl::Appender::CloudWatchLogs
project:
  author:
    mailto: rclauer@gmail.com
    name: 'Rob Lauer'
  description: Log::Log4perl::Appender::CloudWatchLogs
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: http://github.com/rlauer6/Log-Log4perl-Appender-CloudWatchLogs/issues
  homepage: http://github.com/rlauer6/Log-Log4perl-Appender-CloudWatchLogs.git
  repository:
    type: git
    url: git://github.com/rlauer6/Log-Log4perl-Appender-CloudWatchLogs.git
    web: http://github.com/rlauer6/Log-Log4perl-Appender-CloudWatchLogs.git
